### ISSUE TITLE
Unable to deploy using "Deploy with Workers" button

### ISSUE THREAD

**Issue by Izzy2401** [awaitlink/qr-worker#2]
Please see attached screenshot when I attempt to deploy. 

![Screenshot 2024-03-09 213228](https://github.com/awaitlink/qr-worker/assets/136386685/c9653dc8-5f4d-481f-a025-15001c3eb0c5)

**Comment by awaitlink** [comment]
Thanks for the report and sorry for the delay!

Should be fixed now, I've also taken the chance to upgrade to support more modern versions of wrangler, etc.

Glad this is still a useful little project :)
